# Generated by Django 5.0.1 on 2024-01-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('superuser', models.BooleanField()),
                ('dni', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
    ]
